# Assignment 2A

**Name**: RAHUL NARAYAN                              </br>
**Roll No.**: 210806

In [3]:
!pip install gymnasium
# import
import gymnasium as gym
import copy
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.font_manager
import random

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 953.9/953.9 kB 8.8 MB/s eta 0:00:00


In [4]:
'''
Represents a Stochastic Maze problem Gym Environment which provides a Fully observable
MDP
'''
class StochasticMazeEnv(gym.Env):
    '''
    StochasticMazeEnv represents the Gym Environment for the Stochastic Maze environment
    States : [0,1,2,3,4,5,6,7,8,9,10,11]
    Actions : ["Left":0, "Up":1, "Right":2, "Down":3]
    '''
    metadata = {'render.modes': ['human']}

    def __init__(self,initial_state=0,no_states=12,no_actions=4):
        '''
        Constructor for the StochasticMazeEnv class

        Args:
            initial_state : starting state of the agent
            no_states : The no. of possible states which is 12
            no_actions : The no. of possible actions which is 4

        '''
        self.initial_state = initial_state
        self.state = self.initial_state
        self.nA = no_actions
        self.nS = no_states
        self.actions_dict = {"L":0, "U":1, "R":2, "D":3}
        self.prob_dynamics = {
            0: {
                0: [(0.8, 0, -0.01, False), (0.1, 0, -0.01, False), (0.1, 4, -0.01, False)],
                1: [(0.8, 0, -0.01, False), (0.1, 0, -0.01, False), (0.1, 1, -0.01, False)],
                2: [(0.8, 1, -0.01, False), (0.1, 0, -0.01, False), (0.1, 4, -0.01, False)],
                3: [(0.8, 4, -0.01, False), (0.1, 0, -0.01, False), (0.1, 1, -0.01, False)],
            },
            1: {
                0: [(0.8, 0, -0.01, False), (0.1, 1, -0.01, False), (0.1, 1, -0.01, False)],
                1: [(0.8, 1, -0.01, False), (0.1, 0, -0.01, False), (0.1, 2, -0.01, False)],
                2: [(0.8, 2, -0.01, False), (0.1, 1, -0.01, False), (0.1, 1, -0.01, False)],
                3: [(0.8, 1, -0.01, False), (0.1, 0, -0.01, False), (0.1, 2, -0.01, False)],
            },
            2: {
                0: [(0.8, 1, -0.01, False), (0.1, 2, -0.01, False), (0.1, 6, -0.01, False)],
                1: [(0.8, 2, -0.01, False), (0.1, 1, -0.01, False), (0.1, 3, +1, True)],
                2: [(0.8, 3, +1, True), (0.1, 2, -0.01, False), (0.1, 6, -0.01, False)],
                3: [(0.8, 6, -0.01, False), (0.1, 1, -0.01, False), (0.1, 3, +1, True)],
            },
            3: {
                0: [(0.8, 3, 0, True), (0.1, 3, 0, True), (0.1, 3, 0, True)],
                1: [(0.8, 3, 0, True), (0.1, 3, 0, True), (0.1, 3, 0, True)],
                2: [(0.8, 3, 0, True), (0.1, 3, 0, True), (0.1, 3, 0, True)],
                3: [(0.8, 3, 0, True), (0.1, 3, 0, True), (0.1, 3, 0, True)],
            },
            4: {
                0: [(0.8, 4, -0.01, False), (0.1, 0, -0.01, False), (0.1, 8, -0.01, False)],
                1: [(0.8, 0, -0.01, False), (0.1, 4, -0.01, False), (0.1, 4, -0.01, False)],
                2: [(0.8, 4, -0.01, False), (0.1, 0, -0.01, False), (0.1, 8, -0.01, False)],
                3: [(0.8, 8, -0.01, False), (0.1, 4, -0.01, False), (0.1, 4, -0.01, False)],
            },
            5: {
                0: [(0.8, 5, 0, True), (0.1, 5, 0, True), (0.1, 5, 0, True)],
                1: [(0.8, 5, 0, True), (0.1, 5, 0, True), (0.1, 5, 0, True)],
                2: [(0.8, 5, 0, True), (0.1, 5, 0, True), (0.1, 5, 0, True)],
                3: [(0.8, 5, 0, True), (0.1, 5, 0, True), (0.1, 5, 0, True)],
            },
            6: {
                0: [(0.8, 6, -0.01, False), (0.1, 2, -0.01, False), (0.1, 10, -0.01, False)],
                1: [(0.8, 2, -0.01, False), (0.1, 6, -0.01, False), (0.1, 7, -1, True)],
                2: [(0.8, 7, -1, True), (0.1, 2, -0.01, False), (0.1, 10, -0.01, False)],
                3: [(0.8, 10, -0.01, False), (0.1, 6, -0.01, False), (0.1, 7, -1, True)],
            },
            7: {
                0: [(0.8, 7, 0, True), (0.1, 7, 0, True), (0.1, 7, 0, True)],
                1: [(0.8, 7, 0, True), (0.1, 7, 0, True), (0.1, 7, 0, True)],
                2: [(0.8, 7, 0, True), (0.1, 7, 0, True), (0.1, 7, 0, True)],
                3: [(0.8, 7, 0, True), (0.1, 7, 0, True), (0.1, 7, 0, True)],
            },
            8: {
                0: [(0.8, 8, -0.01, False), (0.1, 8, -0.01, False), (0.1, 4, -0.01, False)],
                1: [(0.8, 4, -0.01, False), (0.1, 8, -0.01, False), (0.1, 9, -0.01, False)],
                2: [(0.8, 9, -0.01, False), (0.1, 8, -0.01, False), (0.1, 4, -0.01, False)],
                3: [(0.8, 8, -0.01, False), (0.1, 8, -0.01, False), (0.1, 9, -0.01, False)],
            },
            9: {
                0: [(0.8, 8, -0.01, False), (0.1, 9, -0.01, False), (0.1, 9, -0.01, False)],
                1: [(0.8, 9, -0.01, False), (0.1, 8, -0.01, False), (0.1, 10, -0.01, False)],
                2: [(0.8, 10, -0.01, False), (0.1, 9, -0.01, False), (0.1, 9, -0.01, False)],
                3: [(0.8, 9, -0.01, False), (0.1, 8, -0.01, False), (0.1, 10, -0.01, False)]
            },
            10: {
                0: [(0.8, 9, -0.01, False), (0.1, 6, -0.01, False), (0.1, 10, -0.01, False)],
                1: [(0.8, 6, -0.01, False), (0.1, 9, -0.01, False), (0.1, 11, -0.01, False)],
                2: [(0.8, 11, -0.01, False), (0.1, 6, -0.01, False), (0.1, 10, -0.01, False)],
                3: [(0.8, 10, -0.01, False), (0.1, 9, -0.01, False), (0.1, 11, -0.01, False)]
            },
            11: {
                0: [(0.8, 10, -0.01, False), (0.1, 7, -1, True), (0.1, 11, -0.01, False)],
                1: [(0.8, 7, -1, True), (0.1, 10, -0.01, False), (0.1, 11, -0.01, False)],
                2: [(0.8, 11, -0.01, False), (0.1, 7, -1, True), (0.1, 11, -0.01, False)],
                3: [(0.8, 11, -0.01, False), (0.1, 11, -0.01, False), (0.1, 10, -0.01, False)]
            }
        }
        self.reset()

    def reset(self):
        '''
        Resets the environment
        Returns:
            observations containing player's current state
        '''
        self.state = self.initial_state
        return self.get_obs()

    def get_obs(self):
        '''
        Returns the player's state as the observation of the environment
        '''
        return (self.state)

    def render(self, mode='human'):
        '''
        Renders the environment
        '''
        print("Current state: {}".format(self.state))

    def sample_action(self):
        '''
        Samples and returns a random action from the action space
        '''
        return random.randint(0, self.nA)
    def P(self):
        '''
        Defines and returns the probabilty transition matrix which is in the form of a nested dictionary
        '''
        self.prob_dynamics = {
            0: {
                0: [(0.8, 0, -0.01, False), (0.1, 0, -0.01, False), (0.1, 4, -0.01, False)],
                1: [(0.8, 0, -0.01, False), (0.1, 0, -0.01, False), (0.1, 1, -0.01, False)],
                2: [(0.8, 1, -0.01, False), (0.1, 0, -0.01, False), (0.1, 4, -0.01, False)],
                3: [(0.8, 4, -0.01, False), (0.1, 0, -0.01, False), (0.1, 1, -0.01, False)],
            },
            1: {
                0: [(0.8, 0, -0.01, False), (0.1, 1, -0.01, False), (0.1, 1, -0.01, False)],
                1: [(0.8, 1, -0.01, False), (0.1, 0, -0.01, False), (0.1, 2, -0.01, False)],
                2: [(0.8, 2, -0.01, False), (0.1, 1, -0.01, False), (0.1, 1, -0.01, False)],
                3: [(0.8, 1, -0.01, False), (0.1, 0, -0.01, False), (0.1, 2, -0.01, False)],
            },
            2: {
                0: [(0.8, 1, -0.01, False), (0.1, 2, -0.01, False), (0.1, 6, -0.01, False)],
                1: [(0.8, 2, -0.01, False), (0.1, 1, -0.01, False), (0.1, 3, +1, True)],
                2: [(0.8, 3, +1, True), (0.1, 2, -0.01, False), (0.1, 6, -0.01, False)],
                3: [(0.8, 6, -0.01, False), (0.1, 1, -0.01, False), (0.1, 3, +1, True)],
            },
            3: {
                0: [(0.8, 3, 0, True), (0.1, 3, 0, True), (0.1, 3, 0, True)],
                1: [(0.8, 3, 0, True), (0.1, 3, 0, True), (0.1, 3, 0, True)],
                2: [(0.8, 3, 0, True), (0.1, 3, 0, True), (0.1, 3, 0, True)],
                3: [(0.8, 3, 0, True), (0.1, 3, 0, True), (0.1, 3, 0, True)],
            },
            4: {
                0: [(0.8, 4, -0.01, False), (0.1, 0, -0.01, False), (0.1, 8, -0.01, False)],
                1: [(0.8, 0, -0.01, False), (0.1, 4, -0.01, False), (0.1, 4, -0.01, False)],
                2: [(0.8, 4, -0.01, False), (0.1, 0, -0.01, False), (0.1, 8, -0.01, False)],
                3: [(0.8, 8, -0.01, False), (0.1, 4, -0.01, False), (0.1, 4, -0.01, False)],
            },
            5: {
                0: [(0.8, 5, 0, True), (0.1, 5, 0, True), (0.1, 5, 0, True)],
                1: [(0.8, 5, 0, True), (0.1, 5, 0, True), (0.1, 5, 0, True)],
                2: [(0.8, 5, 0, True), (0.1, 5, 0, True), (0.1, 5, 0, True)],
                3: [(0.8, 5, 0, True), (0.1, 5, 0, True), (0.1, 5, 0, True)],
            },

            6: {
                0: [(0.8, 6, -0.01, False), (0.1, 2, -0.01, False), (0.1, 10, -0.01, False)],
                1: [(0.8, 2, -0.01, False), (0.1, 6, -0.01, False), (0.1, 7, -1, True)],
                2: [(0.8, 7, -1, True), (0.1, 2, -0.01, False), (0.1, 10, -0.01, False)],
                3: [(0.8, 10, -0.01, False), (0.1, 6, -0.01, False), (0.1, 7, -1, True)],
            },
            7: {
                0: [(0.8, 7, 0, True), (0.1, 7, 0, True), (0.1, 7, 0, True)],
                1: [(0.8, 7, 0, True), (0.1, 7, 0, True), (0.1, 7, 0, True)],
                2: [(0.8, 7, 0, True), (0.1, 7, 0, True), (0.1, 7, 0, True)],
                3: [(0.8, 7, 0, True), (0.1, 7, 0, True), (0.1, 7, 0, True)],
            },
            8: {
                0: [(0.8, 8, -0.01, False), (0.1, 8, -0.01, False), (0.1, 4, -0.01, False)],
                1: [(0.8, 4, -0.01, False), (0.1, 8, -0.01, False), (0.1, 9, -0.01, False)],
                2: [(0.8, 9, -0.01, False), (0.1, 8, -0.01, False), (0.1, 4, -0.01, False)],
                3: [(0.8, 8, -0.01, False), (0.1, 8, -0.01, False), (0.1, 9, -0.01, False)],
            },
            9: {
                0: [(0.8, 8, -0.01, False), (0.1, 9, -0.01, False), (0.1, 9, -0.01, False)],
                1: [(0.8, 9, -0.01, False), (0.1, 8, -0.01, False), (0.1, 10, -0.01, False)],
                2: [(0.8, 10, -0.01, False), (0.1, 9, -0.01, False), (0.1, 9, -0.01, False)],
                3: [(0.8, 9, -0.01, False), (0.1, 8, -0.01, False), (0.1, 10, -0.01, False)]
            },
            10: {
                0: [(0.8, 9, -0.01, False), (0.1, 6, -0.01, False), (0.1, 10, -0.01, False)],
                1: [(0.8, 6, -0.01, False), (0.1, 9, -0.01, False), (0.1, 11, -0.01, False)],
                2: [(0.8, 11, -0.01, False), (0.1, 6, -0.01, False), (0.1, 10, -0.01, False)],
                3: [(0.8, 10, -0.01, False), (0.1, 9, -0.01, False), (0.1, 11, -0.01, False)]
            },
            11: {
                0: [(0.8, 10, -0.01, False), (0.1, 7, -1, True), (0.1, 11, -0.01, False)],
                1: [(0.8, 7, -1, True), (0.1, 10, -0.01, False), (0.1, 11, -0.01, False)],
                2: [(0.8, 11, -0.01, False), (0.1, 7, -1, True), (0.1, 11, -0.01, False)],
                3: [(0.8, 11, -0.01, False), (0.1, 11, -0.01, False), (0.1, 10, -0.01, False)]
            }
        }
        return self.prob_dynamics


    def step(self, action):
        '''
        Performs the given action
        Args:
            action : action from the action_space to be taking in the environment
        Returns:
            observation - returns current state
            reward - reward obtained after taking the given action
            done - True if the episode is complete else False
        '''
        if action >= self.nA:
            action = self.nA-1

        index = np.random.choice(3,1,p=[0.8,0.1,0.1])[0]

        dynamics_tuple = self.prob_dynamics[self.state][action][index]
        self.state = dynamics_tuple[1]


        return self.state, dynamics_tuple[2], dynamics_tuple[3]

In [5]:
env = StochasticMazeEnv()
env.reset()
num_states = env.nS
num_actions = env.nA
l=env.prob_dynamics[1][2][1]

## Test Cases for checking the environment

## Example: Random Policy

In [6]:
is_Terminal = False
env.reset()
count = 0
total_reward = 0

print("Action\t" , "State\t" , "Reward\t" , "is_Terminal")

while not is_Terminal:
    count += 1

    rand_action = np.random.choice(4,1)[0]  #0 -> LEFT, 1 -> UP, 2 -> RIGHT, 3 -> DOWN
    state, reward, is_Terminal = env.step(rand_action)
    total_reward += reward

    print("  ", rand_action, "\t  ", state, "\t", reward, "\t  ", is_Terminal)
print("Total Number of steps to Reach Terminal:", count)
print("Final Reward:", total_reward)

Action	 State	 Reward	 is_Terminal
   3 	   4 	 -0.01 	   False
   3 	   8 	 -0.01 	   False
   1 	   4 	 -0.01 	   False
   1 	   0 	 -0.01 	   False
   0 	   0 	 -0.01 	   False
   1 	   0 	 -0.01 	   False
   2 	   1 	 -0.01 	   False
   2 	   2 	 -0.01 	   False
   1 	   2 	 -0.01 	   False
   1 	   2 	 -0.01 	   False
   1 	   1 	 -0.01 	   False
   2 	   1 	 -0.01 	   False
   1 	   1 	 -0.01 	   False
   0 	   0 	 -0.01 	   False
   2 	   1 	 -0.01 	   False
   3 	   1 	 -0.01 	   False
   3 	   1 	 -0.01 	   False
   2 	   2 	 -0.01 	   False
   2 	   3 	 1 	   True
Total Number of steps to Reach Terminal: 19
Final Reward: 0.82


### The random policy takes large number of steps to reach some terminal state which should be much higher than the number of the steps taken by a all 'Right' policy

## Example: Right Policy

In [7]:
is_Terminal = False
env.reset()
count = 0
total_reward = 0

print("Action\t" , "State\t" , "Reward\t" , "is_Terminal")

while not is_Terminal:
    count += 1

    right_action = 2  #0 -> LEFT, 1 -> UP, 2 -> RIGHT, 3 -> DOWN
    state, reward, is_Terminal = env.step(right_action)

    total_reward += reward

    print("  ", right_action, "\t  ", state, "\t", reward, "\t  ", is_Terminal)

print("Total Number of steps to Reach Terminal:", count)
print("Final Reward:", total_reward)

Action	 State	 Reward	 is_Terminal
   2 	   1 	 -0.01 	   False
   2 	   2 	 -0.01 	   False
   2 	   3 	 1 	   True
Total Number of steps to Reach Terminal: 3
Final Reward: 0.98


### The right policy most of the time reaches the goal state in just 3 steps which is expected

***

## Q1. Find an optimal policy to navigate the given environment using Policy Iteration

###  Method 1

#### This is the method according to the actual stochastic set-up

In [8]:
env = StochasticMazeEnv()
env.reset()

0

In [9]:
def reward(s,a, prob_dynamics):
    s=int(s)
    a = int(a)
    x=0
    for j in range(3):
        x = x + (prob_dynamics[s][a][j][0])*(prob_dynamics[s][a][j][2])
    return x

* $R_s^a$ function

In [10]:
def p_ss(policy, prob_dynamics):
    P = np.zeros([12,12])
    for i in range(12):
            for j in range(12):
                if j == prob_dynamics[i][policy[i]][0][1]:
                    P[i][j] = 0.8
                if j == prob_dynamics[i][policy[i]][1][1]:
                    P[i][j] = P[i][j] + 0.1
                if j == prob_dynamics[i][policy[i]][2][1]:
                    P[i][j] = P[i][j] + 0.1
                else:
                    P[i][j] = P[i][j] + 0
    return P

this function, gives us $P_{ss'}^\pi$ matrix 12*12
 - for i in range(12): represents for current state 'i'
 - for j in range(12): represents for the corresponding next state 'j' and checks if it can go to this state and gives the corresponding probability

In [11]:
def val_func1(policy, P_ss, gamma, prob_dynamics):
    a = np.eye(12)-gamma*P_ss
    A = np.matrix(a)
    r = np.array(np.zeros(12))
    for i in range(12):
        r[i] = reward(i,policy[i], prob_dynamics)
    R = np.transpose(r)
    A_inv = np.linalg.inv(A)
    V_New = np.dot(A_inv, R)
    return V_New

- function of $V_{\pi}$ matrix, (12,1)

In [12]:
def policy_improvement1(policy,V, P_ss,gamma,prob_dynamics):
    V_matrix = V.reshape(12,1)
    q = np.zeros([12,4])
    policy_New = np.zeros(12)
    for i in range(12):
        A = [0,0,0,0]   # to store values of action value function for every action
        for j in range(4):
            x = 0
            y = 0
            for k in range(3):
                x = x + (prob_dynamics[i][j][k][0])*(prob_dynamics[i][j][k][2])
            for k in range(3):
                y = y + gamma*(float(V_matrix[prob_dynamics[i][j][k][1]][0]))*(prob_dynamics[i][j][k][0])
            A[j] = x+y
        policy_New[i] = np.argmax(A)
    return policy_New

Policy improvement function, gives $\pi_k$
- checks for the action for which gives max{$q_s^a$}
- x is the probabilistic reward for intended and orthogonal actions
- y is $\Sigma P_{ss'}^{\pi}*V_{\pi}(s')$

In [14]:
gamma = 0.69
policy = [3 for i in range(12)]

# policy = []
# for i in range(12):
#     element = int(input(f"Enter element {i + 1}: "))
#     array.append(element)

count = 0
prob_dynamics = env.P()
P_ss = p_ss(policy, prob_dynamics)
V_0 = val_func1(policy, P_ss, gamma, prob_dynamics)
print(policy)
policy_new = policy_improvement1(policy,V_0,P_ss,gamma,prob_dynamics)
print(policy_new)
count = 1
while((policy_new!=policy).any()):
    policy = policy_new
    P_ss = p_ss(policy, prob_dynamics)
    V_new = val_func1(policy, P_ss, gamma, prob_dynamics)
    policy_new = policy_improvement1(policy,V_new, P_ss,gamma,prob_dynamics)
    count += 1
    print(policy_new)

[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
[2. 2. 2. 0. 1. 0. 0. 0. 0. 0. 3. 3.]
[2. 2. 2. 0. 1. 0. 1. 0. 1. 0. 1. 3.]
[2. 2. 2. 0. 1. 0. 1. 0. 1. 2. 1. 0.]
[2. 2. 2. 0. 1. 0. 1. 0. 1. 2. 1. 0.]


<ipython-input-12-be3033f3824d>:13: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y = y + gamma*(float(V_matrix[prob_dynamics[i][j][k][1]][0]))*(prob_dynamics[i][j][k][0])


#### - uncomment the commented lines to take the input of customized initial policies

In [15]:
print(count)

4


- counts the number of iterations our policy took

#### Inferences
- the actual optimistic policy will be [ 2, 2, 2, -, 1, -, 1, -, 1 (or) 2, 2, 1, 0]
- '-' means any action doesn't matter as the episode terminates in these states
- as we can see, the optimal policy we got is almost the actual optimal policy expect for the state 11
- for different $\gamma$, the converged policy changes
- for our set-up, **$\gamma $** from **0.69 to 0.9** seem to give us the actual optimal policy
- it took __4 updates__ of policies for the policy to converge

### Method 2

#### This method considers deterministic setup for the state we are currently in and considers stochastic setup for other states
- meaning we are taking intended action with probability 1 from the current state and taking the actual stochastic setup from the next state
- the function used in Method 1 are changed accordingly

In [16]:
def val_func(policy, P_ss, gamma, prob_dynamics):
    a = np.eye(12)-gamma*P_ss
    A = np.matrix(a)
    r = [(prob_dynamics[i][policy[i]][0][2]) for i in range(12)]
    R = np.transpose(r)
    A_inv = np.linalg.inv(A)
    V_New = np.dot(A_inv, R)
    return V_New

In [17]:
def policy_improvement(policy,V, prob_dynamics,gamma):
    V = np.array(np.transpose(V))
    q = np.zeros([12,4])
    policy_New = np.zeros(12)
    for i in range(12):
        for j in range(4):
            q[i][j]= prob_dynamics[i][j][0][2] + gamma*(V[prob_dynamics[i][j][0][1]])
        if q[i][int(policy[i])] != np.max(q[i]):
            policy_New[i] = np.argmax(q[i])
        else:
            policy_New[i] = policy[i]
    return policy_New

In [18]:
# Let our initial policy be 'policy' givese the optimal action(indicated by 0,1,2,3) for every state(index)
gamma = 0.8588

policy = [2 for i in range(12)]
count = 0;
print(policy)
prob_dynamics = env.P()
P_ss = p_ss(policy, prob_dynamics)
V = val_func(policy, P_ss, gamma, prob_dynamics)
policy_new = policy_improvement(policy,V,prob_dynamics,gamma)
count = 1
print(policy_new)
while((policy_new!=policy).any()):
    policy = policy_new
    P_ss = p_ss(policy, prob_dynamics)
    V_new = val_func(policy, P_ss, gamma, prob_dynamics)
    policy_new = policy_improvement(policy,V_new, prob_dynamics,gamma)
    count += 1;
    print(policy_new)

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
[2. 2. 2. 2. 1. 2. 1. 2. 1. 0. 2. 2.]
[2. 2. 2. 2. 1. 2. 1. 2. 1. 0. 1. 0.]
[2. 2. 2. 2. 1. 2. 1. 2. 1. 2. 1. 0.]
[2. 2. 2. 2. 1. 2. 1. 2. 1. 2. 1. 0.]


<ipython-input-17-90d18128bd3c>:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  q[i][j]= prob_dynamics[i][j][0][2] + gamma*(V[prob_dynamics[i][j][0][1]])


In [19]:
print(count)

4


#### Inferences
- this is simpler to code and converges to the actual optimal policy
- for our set-up, **$\gamma $** from **0.0016 to 0.8588** seem to give us the actual optimal policy
- for $\gamma > 0.8588$, our algorithm seem to oscillate for the states just before the terminal states
- this algorithm also converges in __4__ updates

## Q2. Find an optimal policy to navigate the given environment using Value Iteration

###  Method 1

#### This is the method according to the actual stochastic set-up

In [20]:
env.reset()

0

In [21]:
def P_ss_every_state(s,a,prob_dynamics):
    P_ssa = np.zeros(12)
    for j in range(12):
        if j == prob_dynamics[s][a][0][1]:
            P_ssa[j] = 0.8
        if j == prob_dynamics[s][a][1][1]:
            P_ssa[j] = P_ssa[j] + 0.1
        if j == prob_dynamics[s][a][2][1]:
            P_ssa[j] = P_ssa[j] + 0.1
        else:
            P_ssa[j] = P_ssa[j] + 0
    return P_ssa

- gives $P_{ss'}^a$ value

In [22]:
def p_ss(policy, prob_dynamics):
    P = np.zeros([12,12])
    for i in range(12):
            for j in range(12):
                if j == prob_dynamics[i][policy[i]][0][1]:
                    P[i][j] = 0.8
                if j == prob_dynamics[i][policy[i]][1][1]:
                    P[i][j] = P[i][j] + 0.1
                if j == prob_dynamics[i][policy[i]][2][1]:
                    P[i][j] = P[i][j] + 0.1
                else:
                    P[i][j] = P[i][j] + 0
    return P

this function, gives us $P_{ss'}^\pi$ matrix 12*12
 - for i in range(12): represents for current state 'i'
 - for j in range(12): represents for the corresponding next state 'j' and checks if it can go to this state and gives the corresponding probability

In [23]:
def reward(s,a, prob_dynamics):
    s=int(s)
    a = int(a)
    x=0
    for j in range(3):
        x = x + (prob_dynamics[s][a][j][0])*(prob_dynamics[s][a][j][2])
    return x

* $R_s^a$ function

In [24]:
def val_func(policy, P_ss, gamma, prob_dynamics):
    a = np.eye(12)-gamma*P_ss
    A = np.matrix(a)
    r = np.array(np.zeros(12))
    for i in range(12):
        r[i] = reward(i,policy[i], prob_dynamics)
    R = np.transpose(r)
    A_inv = np.linalg.inv(A)
    V_New = np.dot(A_inv, R)
    return V_New

- function of $V_{\pi}$ matrix, (12,1)

In [25]:
def val_iter_func(V, gamma, prob_dynamics,policy_P):
    V_iter_new = np.matrix(np.zeros([12,1]))
    V_matrix = V.reshape(12,1)
    P_n = np.zeros(12)
    for i in range(12):
        A = [0,0,0,0]
        for j in range(4):
            x = 0
            y = 0
            for k in range(3):
                x = x + (prob_dynamics[i][j][k][0])*(prob_dynamics[i][j][k][2])
            for k in range(3):
                y = y + gamma*(float(V_matrix[prob_dynamics[i][j][k][1]][0]))*(prob_dynamics[i][j][k][0])
            A[j] = x+y
        V_iter_new[i][0] = np.max(A)
        P_n[i] = np.argmax(A)
    return V_iter_new, P_n

- this is value improvement function for value iteration algorithm
- i.e., $V_{k+1} = max_a${$ R_s^a + \gamma (\Sigma P_{ss'}^a*V_k(s'))$}

In [26]:
policy = [2 for i in range(12)]
gamma = 0.7
P_ss2 = p_ss(policy, prob_dynamics)
V_0 = val_func(policy, P_ss2, gamma, prob_dynamics)

print(V_0)

V_new = val_iter_func(V_0, gamma, prob_dynamics, policy)[0]

Policy_new = val_iter_func(V_0, gamma, prob_dynamics,policy)[1]

print(Policy_new)
print(np.transpose(V_new))
count = 1
while((V_new != V_0).any()):
    V_0 = V_new
    V_new = val_iter_func(V_0, gamma, prob_dynamics, policy)[0]
    Policy_new = val_iter_func(V_0, gamma, prob_dynamics,policy)[1]
    print(Policy_new)
    print(np.transpose(V_new))
    count+=1

[[ 0.29665009  0.50970821  0.80062332  0.          0.00639977  0.
  -0.76314726  0.         -0.1135658  -0.17154318 -0.24558417 -0.29459459]]
[2. 2. 2. 0. 1. 0. 1. 0. 1. 0. 0. 3.]
[[ 0.29665009  0.50970821  0.80062332  0.          0.15702002  0.
   0.28592875  0.         -0.02637376 -0.0976129  -0.17667538 -0.21278549]]
[2. 2. 2. 0. 1. 0. 1. 0. 1. 0. 1. 3.]
[[ 0.30719351  0.50970821  0.87405865  0.          0.17810685  0.
   0.35936407  0.          0.06925214 -0.03843511  0.12839222 -0.15642213]]
[2. 2. 2. 0. 1. 0. 1. 0. 1. 2. 1. 0.]
[[ 0.30940762  0.55083199  0.88433959  0.          0.18696332  0.
   0.40562833  0.          0.09189703  0.05651873  0.17760387 -0.04804991]]
[2. 2. 2. 0. 1. 0. 1. 0. 1. 2. 1. 0.]
[[ 0.33321188  0.56234665  0.88829775  0.          0.18944313  0.
   0.41462415  0.          0.10508856  0.09737079  0.21774468 -0.01290532]]
[2. 2. 2. 0. 1. 0. 1. 0. 1. 2. 1. 0.]
[[0.34149997 0.56617527 0.88920453 0.         0.20312069 0.
  0.41747043 0.         0.11026031 0.125

<ipython-input-25-feb794149372>:13: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y = y + gamma*(float(V_matrix[prob_dynamics[i][j][k][1]][0]))*(prob_dynamics[i][j][k][0])


[[0.34718135 0.56762071 0.88956037 0.         0.21444367 0.
  0.41844496 0.         0.1290672  0.14205769 0.23601716 0.02491356]]


In [27]:
print(np.transpose(V_new))

[[0.34718135 0.56762071 0.88956037 0.         0.21444367 0.
  0.41844496 0.         0.1290672  0.14205769 0.23601716 0.02491356]]


- this is the converged value function( $V_\pi$) matrix

In [28]:
print(Policy_new)

[2. 2. 2. 0. 1. 0. 1. 0. 1. 2. 1. 0.]


- this is the converged policy( $ \pi$)

In [29]:
print(count)

39


- number of updates this algorithm took

#### Inferences
- the actual optimistic policy will be [ 2, 2, 2, -, 1, -, 1, -, 1 (or) 2, 2, 1, 0]
- '-' means any action doesn't matter as the episode terminates in these states
- as we can see, the optimal policy we got is almost the actual optimal policy expect for the state 11
- for different $\gamma$, the converged policy changes
- for our set-up, **$\gamma $** from **0.69 to 0.9** seem to give us the actual optimal policy
- it took __39 updates__ of policies for the policy to converge

### Method 2

#### This method considers deterministic setup for the state we are currently in and considers stochastic setup for other states
- meaning we are taking intended action with probability 1 from the current state and taking the actual stochastic setup from the next state
- the function used in Method 1 are changed accordingly

In [30]:
env.reset()

0

In [31]:
def P_ss_every_state(s,a,prob_dynamics):
    P_ssa = np.zeros(12)
    for j in range(12):
        if j == prob_dynamics[s][a][0][1]:
            P_ssa[j] = 0.8
        if j == prob_dynamics[s][a][1][1]:
            P_ssa[j] = P_ssa[j] + 0.1
        if j == prob_dynamics[s][a][2][1]:
            P_ssa[j] = P_ssa[j] + 0.1
        else:
            P_ssa[j] = P_ssa[j] + 0
    return P_ssa

- gives $P_{ss'}^a$ value

In [32]:
def p_ss(policy, prob_dynamics):
    P = np.zeros([12,12])
    for i in range(12):
            for j in range(12):
                if j == prob_dynamics[i][policy[i]][0][1]:
                    P[i][j] = 0.8
                if j == prob_dynamics[i][policy[i]][1][1]:
                    P[i][j] = P[i][j] + 0.1
                if j == prob_dynamics[i][policy[i]][2][1]:
                    P[i][j] = P[i][j] + 0.1
                else:
                    P[i][j] = P[i][j] + 0
    return P

this function, gives us $P_{ss'}^\pi$ matrix 12*12
 - for i in range(12): represents for current state 'i'
 - for j in range(12): represents for the corresponding next state 'j' and checks if it can go to this state and gives the corresponding probability

In [33]:
def val_func(policy, P_ss, gamma, prob_dynamics):
    a = np.eye(12)-gamma*P_ss
    A = np.matrix(a)
    r = [prob_dynamics[i][policy[i]][0][2] for i in range(12)]
    R = np.transpose(np.matrix(r))
    A_inv = np.linalg.inv(A)
    V_New = np.dot(A_inv, R)
    return V_New

- function of $V_{\pi}$ matrix, (12,1)

In [34]:
def val_iter_func(V, gamma, prob_dynamics,policy_P):
    V_iter_new = np.matrix(np.zeros([12,1]))
    P_n = np.zeros(12)
    for i in range(12):
        A = [0,0,0,0]
        for j in range(4):
            V_s_next = np.matrix(np.zeros([12,1]))
            for m in range(12):
                #print(m)
                V_s_next[m][0] = V[prob_dynamics[m][j][0][1]][0]
            A[j] = prob_dynamics[i][j][0][2] + gamma*(np.dot(P_ss_every_state(i,j,prob_dynamics),V))
        V_iter_new[i][0] = np.max(A)
        P_n[i] = np.argmax(A)
    return V_iter_new.reshape(12,1), np.array(P_n)

- this is value improvement function for value iteration algorithm
- i.e., $V_{k+1} = max_a${$ R_s^a + \gamma (\Sigma P_{ss'}^a*V_k(s'))$}

In [35]:
policy = [2 for i in range(12)]
gamma = 0.85
prob_dynamics= env.P()
P_ss2 = p_ss(policy, prob_dynamics)
V_0 = val_func(policy, P_ss2, gamma, prob_dynamics)
print(policy)
print(np.transpose(V_0))
V_new = val_iter_func(V_0, gamma, prob_dynamics, policy)[0]
Policy_new = val_iter_func(V_0, gamma, prob_dynamics,policy)[1]
print(Policy_new)
print(np.transpose(V_new))
count = 1
while((V_new != V_0).any()):
    V_0 = V_new
    V_new = val_iter_func(V_0, gamma, prob_dynamics, policy)[0]
    Policy_new = val_iter_func(V_0, gamma, prob_dynamics,policy)[1]
    print(Policy_new)
    print(np.transpose(V_new))
    count+=1

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
[[ 0.6029987   0.81291157  1.00693618  0.          0.1054581   0.
  -0.92533405  0.         -0.08833291 -0.1173361  -0.12851318 -0.04255319]]
[2. 2. 2. 0. 1. 0. 1. 0. 1. 0. 3. 2.]
[[ 0.6029987   0.81291157  1.00693618  0.          0.41796699  0.
   0.59606321  0.          0.04422964 -0.09001352 -0.11097956 -0.04255319]]
[2. 2. 2. 0. 1. 0. 1. 0. 1. 0. 1. 2.]
[[ 0.62956195  0.81291157  1.13625495  0.          0.4710935   0.
   0.72538198  0.          0.27032592  0.00477386  0.38405481 -0.04255319]]
[2. 2. 2. 0. 1. 0. 1. 0. 1. 2. 1. 0.]
[[0.63633558 0.90084833 1.15823914 0.         0.49818802 0.
  0.82431083 0.         0.33372706 0.25196883 0.4800485  0.24754025]]
[2. 2. 2. 0. 1. 0. 1. 0. 1. 2. 1. 0.]
[[0.69901137 0.93074683 1.16851675 0.         0.50740016 0.
  0.84766904 0.         0.37855201 0.35926768 0.59298964 0.3374739 ]]
[2. 2. 2. 0. 1. 0. 1. 0. 1. 2. 1. 0.]
[[0.72545282 0.94281835 1.17137579 0.         0.55158576 0.
  0.85664326 0.         0.3

In [36]:
print(np.transpose(V_new))

[[0.75019834 0.94884242 1.17285178 0.         0.60257213 0.
  0.86069859 0.         0.48608165 0.52959605 0.66112459 0.4803986 ]]


- this is the converged value function( $V_\pi$) matrix

In [37]:
print(Policy_new)

[2. 2. 2. 0. 1. 0. 1. 0. 1. 2. 1. 0.]


- this is the converged policy( $ \pi$)

In [38]:
print(count)

49


- the updates it took for our algorithm to converge

#### Inferences
- this is simpler to code and converges to the actual optimal policy
- for our set-up, **$\gamma $** from **0.0016 to 0.8588** seem to give us the actual optimal policy
- for $\gamma > 0.8588$, our algorithm seem to oscillate for the states just before the terminal states
- this algorithm also converges in __48__ updates

## Q3. Compare PI and VI in terms of convergence. Is the policy obtained by both same?

### Answer:
- #### Both PI and VI converge to the same policy, but PI converges in fewer iterations than VI
- #### In VI, the policy convergence took the same number of iterations as PI
- #### But the convergence of value function in VI took far more iterations
